from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Callable, Sequence

from .base import AdapterResult, command_exists


PLUGIN_YAML = """name: memnetai-memory
version: 0.1.0
description: MemNetAI long-term memory lifecycle integration
hooks:
  - pre_llm_call
  - post_llm_call
  - on_session_finalize
  - on_session_reset
"""


def _plugin_source(executable: Path) -> str:
    exe = json.dumps(str(executable))
    return f'''"""Generated by memnetai-agent-integration."""
import json
import subprocess

EXECUTABLE = {exe}

def _run(command, payload, timeout):
    try:
        result = subprocess.run(
            [EXECUTABLE, command], input=json.dumps(payload, ensure_ascii=False),
            text=True, capture_output=True, timeout=timeout, check=False,
        )
        if result.returncode != 0 or not result.stdout.strip():
            return {{}}
        return json.loads(result.stdout)
    except Exception:
        return {{}}

def _before(session_id, user_message, **kwargs):
    payload = dict(kwargs)
    payload.update({{"session_id": session_id, "prompt": user_message, "hook_event_name": "pre_llm_call", "host": "hermes"}})
    result = _run("hook-before", payload, 5)
    context = result.get("context") or result.get("additionalContext") or ""
    return {{"context": context}} if context else {{}}

def _after(session_id, user_message, assistant_response, **kwargs):
    payload = dict(kwargs)
    payload.update({{"session_id": session_id, "prompt": user_message, "last_assistant_message": assistant_response, "hook_event_name": "post_llm_call", "host": "hermes"}})
    _run("hook-after", payload, 15)

def _flush(session_id, **kwargs):
    payload = dict(kwargs)
    payload.update({{"session_id": session_id, "host": "hermes"}})
    _run("flush-session", payload, 15)

def register(ctx):
    ctx.register_hook("pre_llm_call", _before)
    ctx.register_hook("post_llm_call", _after)
    ctx.register_hook("on_session_finalize", _flush)
    ctx.register_hook("on_session_reset", _flush)
'''


class HermesAdapter:
    name = "hermes"

    def __init__(self, runner: Callable[[Sequence[str]], subprocess.CompletedProcess[str]] | None = None) -> None:
        self.runner = runner or self._run

    @staticmethod
    def _run(args: Sequence[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            list(args), capture_output=True, text=True, encoding="utf-8", errors="replace",
            check=False,
        )

    @property
    def plugin_dir(self) -> Path:
        override = os.environ.get("HERMES_HOME")
        if override:
            home = Path(override).expanduser()
        elif os.name == "nt":
            base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
            home = base / "hermes"
        else:
            home = Path.home() / ".hermes"
        return home / "plugins" / "memnetai-memory"

    def detect(self) -> bool:
        return command_exists("hermes", "hermes.exe") or self.plugin_dir.parent.parent.exists()

    def install(self, executable: Path, *, dry_run: bool = False) -> AdapterResult:
        files = {"plugin.yaml": PLUGIN_YAML, "__init__.py": _plugin_source(executable)}
        entry = self.plugin_dir / "__init__.py"
        if entry.exists() and "Generated by memnetai-agent-integration" not in entry.read_text(
            encoding="utf-8"
        ):
            raise RuntimeError(f"Hermes plugin name conflict: {self.plugin_dir}")
        changed = any(not (self.plugin_dir / name).exists() or
                      (self.plugin_dir / name).read_text(encoding="utf-8") != value
                      for name, value in files.items())
        previous = {
            name: (self.plugin_dir / name).read_text(encoding="utf-8")
            if (self.plugin_dir / name).exists() else None
            for name in files
        }
        if changed and not dry_run:
            self.plugin_dir.mkdir(parents=True, exist_ok=True)
            for name, value in files.items():
                target = self.plugin_dir / name
                temporary = target.with_suffix(target.suffix + ".tmp")
                temporary.write_text(value, encoding="utf-8")
                os.replace(temporary, target)
            result = self.runner(("hermes", "plugins", "enable", "--no-allow-tool-override",
                                  "memnetai-memory"))
            if result.returncode != 0:
                for name, content in previous.items():
                    target = self.plugin_dir / name
                    if content is None:
                        target.unlink(missing_ok=True)
                    else:
                        target.write_text(content, encoding="utf-8")
                raise RuntimeError(result.stderr or result.stdout or "Hermes plugin enable failed")
        verified = False if dry_run else self.verify(executable).verified
        return AdapterResult(self.name, self.detect(), not dry_run, verified, "python-plugin",
                             str(self.plugin_dir), "updated" if changed else "already installed")

    def verify(self, executable: Path) -> AdapterResult:
        plugin = self.plugin_dir / "__init__.py"
        text = plugin.read_text(encoding="utf-8") if plugin.exists() else ""
        files_ok = "hook-before" in text and "hook-after" in text and executable.name in text
        enabled = False
        if files_ok:
            try:
                result = self.runner(("hermes", "plugins", "list", "--enabled", "--json"))
                enabled = result.returncode == 0 and "memnetai-memory" in result.stdout
            except OSError:
                enabled = False
        ok = files_ok and enabled
        return AdapterResult(self.name, self.detect(), ok, ok, "python-plugin",
                             str(self.plugin_dir), "plugin found" if ok else "missing")

    def uninstall(self, executable: Path, *, dry_run: bool = False) -> AdapterResult:
        owned = [self.plugin_dir / "__init__.py", self.plugin_dir / "plugin.yaml"]
        entry = self.plugin_dir / "__init__.py"
        if entry.exists() and "Generated by memnetai-agent-integration" not in entry.read_text(
            encoding="utf-8"
        ):
            raise RuntimeError(f"Refusing to remove unowned Hermes plugin: {self.plugin_dir}")
        changed = any(path.exists() for path in owned)
        if not dry_run:
            if changed and command_exists("hermes", "hermes.exe"):
                self.runner(("hermes", "plugins", "disable", "memnetai-memory"))
            for path in owned:
                if path.exists():
                    path.unlink()
            if self.plugin_dir.exists() and not any(self.plugin_dir.iterdir()):
                self.plugin_dir.rmdir()
        return AdapterResult(self.name, self.detect(), False, True, "python-plugin",
                             str(self.plugin_dir), "removed" if changed else "absent")
